create database root_system;
use root_system;

CREATE TABLE B_Employee (
  BEM_CODE VARCHAR(30) NOT NULL,
  BEM_NAME VARCHAR(50) DEFAULT '',
  BEM_PW VARBINARY(200) DEFAULT 0,
  BEM_DEPGU VARCHAR(3) DEFAULT '000',
  BEM_POSGU VARCHAR(3) DEFAULT '000',
  BEM_FACWKYN VARCHAR(1) DEFAULT 'N',
  BEM_FILLER VARCHAR(1000) DEFAULT '',
  BEM_USEYN VARCHAR(1) DEFAULT 'Y',
  BEM_LASTLOGIN DATETIME DEFAULT NULL,
  BEM_SALT VARBINARY(500) DEFAULT 0,
  BEM_PWDATE DATETIME DEFAULT NULL, -- Added column for password date
  BEM_BLOCKNUM INT DEFAULT 0, -- Added column for block number
  FDATE DATETIME DEFAULT NULL,
  FUSER VARCHAR(30) DEFAULT '',
  FFORM VARCHAR(50) DEFAULT '',
  LDATE DATETIME DEFAULT NULL,
  LUSER VARCHAR(30) DEFAULT '',
  LFORM VARCHAR(50) DEFAULT '',
  PRIMARY KEY (BEM_CODE)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE P_Production_Result_Emp (
  PMOE_CODE INT NOT NULL,
  PPR_CODE INT DEFAULT 0,
  BEM_CODE VARCHAR(30) DEFAULT '',
  FDATE DATETIME DEFAULT NULL,
  FUSER VARCHAR(30) DEFAULT '',
  FFORM VARCHAR(50) DEFAULT '',
  LDATE DATETIME DEFAULT NULL,
  LUSER VARCHAR(30) DEFAULT '',
  LFORM VARCHAR(50) DEFAULT '',
  PRIMARY KEY (PMOE_CODE)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE P_Production_Result_Bad (
  PPRB_CODE INT NOT NULL,
  PPR_CODE INT DEFAULT 0,
  PPRB_BADGU VARCHAR(3) DEFAULT '',
  PPRB_BADQTY DECIMAL(19,7) DEFAULT 0,
  FDATE DATETIME DEFAULT NULL,
  FUSER VARCHAR(30) DEFAULT '',
  FFORM VARCHAR(50) DEFAULT '',
  LDATE DATETIME DEFAULT NULL,
  LUSER VARCHAR(30) DEFAULT '',
  LFORM VARCHAR(50) DEFAULT '',
  PRIMARY KEY (PPRB_CODE)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE P_Production_Result (
  PPR_CODE INT NOT NULL,
  PPID_CODE INT DEFAULT 0,
  PPR_PROGU VARCHAR(3) DEFAULT '',
  BMA_CODE VARCHAR(30) DEFAULT '',
  BMO_CODE VARCHAR(30) DEFAULT '',
  BIT_CODE VARCHAR(30) DEFAULT '',
  PPR_DATE DATETIME DEFAULT NULL,
  PPR_DAYGU VARCHAR(1) DEFAULT '',
  PPR_SDATETIME DATETIME DEFAULT NULL,
  PPR_EDATETIME DATETIME DEFAULT NULL,
  PPR_HITCNT INT DEFAULT 0,
  PPR_BLANKHITCNT INT DEFAULT 0,
  PPR_TOTQTY DECIMAL(19,7) DEFAULT 0,
  PPR_GOODQTY DECIMAL(19,7) DEFAULT 0,
  PPR_BADQTY DECIMAL(19,7) DEFAULT 0,
  PPR_FILLER VARCHAR(1000) DEFAULT '',
  FDATE DATETIME DEFAULT NULL,
  FUSER VARCHAR(30) DEFAULT '',
  FFORM VARCHAR(50) DEFAULT '',
  LDATE DATETIME DEFAULT NULL,
  LUSER VARCHAR(30) DEFAULT '',
  LFORM VARCHAR(50) DEFAULT '',
  PRIMARY KEY (PPR_CODE)
) DEFAULT CHARSET=utf8mb4;


CREATE TABLE B_DownTime (
  BDT_CODE INT NOT NULL,
  BMA_CODE VARCHAR(30) DEFAULT NULL,
  BDT_DATE DATETIME DEFAULT NULL,
  BDT_DOWNGU VARCHAR(5) DEFAULT NULL,
  BDT_STIME DATETIME DEFAULT NULL,
  BDT_ETIME DATETIME DEFAULT NULL,
  BDT_FILLER VARCHAR(1000) DEFAULT '',
  PPR_CODE INT DEFAULT NULL,
  FDATE DATETIME DEFAULT NULL,
  FUSER VARCHAR(30) DEFAULT '',
  FFORM VARCHAR(50) DEFAULT '',
  LDATE DATETIME DEFAULT NULL,
  LUSER VARCHAR(30) DEFAULT '',
  LFORM VARCHAR(50) DEFAULT '',
  PRIMARY KEY (BDT_CODE)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE B_CycleTime (
  BCT_CODE INT NOT NULL,
  BCT_GU VARCHAR(1) DEFAULT '',
  BCT_PROGU VARCHAR(3) DEFAULT '000',
  BMA_CODE VARCHAR(30) DEFAULT '',
  BIT_CODE VARCHAR(30) DEFAULT '',
  BCT_DATE DATETIME DEFAULT NULL,
  BCT_CVT INT DEFAULT 0,
  BCT_MCT DECIMAL(19,7) DEFAULT 0,
  BCT_CT DECIMAL(19,7) DEFAULT 0,
  BCT_FILLER VARCHAR(1000) DEFAULT '',
  FDATE DATETIME DEFAULT NULL,
  FUSER VARCHAR(30) DEFAULT '',
  FFORM VARCHAR(50) DEFAULT '',
  LDATE DATETIME DEFAULT NULL,
  LUSER VARCHAR(30) DEFAULT '',
  LFORM VARCHAR(50) DEFAULT '',
  PRIMARY KEY (BCT_CODE)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE B_Machine (
  BMA_CODE VARCHAR(30) NOT NULL,
  BMA_KINDGU VARCHAR(3) DEFAULT '000',
  BMA_NAME VARCHAR(50) DEFAULT '',
  BMA_SPEC VARCHAR(100) DEFAULT '',
  BMA_MODEL VARCHAR(100) DEFAULT '',
  BMA_MAKECOM VARCHAR(100) DEFAULT '',
  BMA_MAKEDATE DATETIME DEFAULT NULL,
  BMA_BUYDATE DATETIME DEFAULT NULL,
  BMA_PROGU VARCHAR(3) DEFAULT '',
  BMA_HOPPER VARCHAR(30) DEFAULT '',
  BWH_CODE VARCHAR(30) DEFAULT '',
  BMO_CODE VARCHAR(30) DEFAULT '',
  BMA_FILLER VARCHAR(1000) DEFAULT '',
  BMA_NOMATTERYN VARCHAR(1) DEFAULT 'N',
  BMA_USEYN VARCHAR(1) DEFAULT 'Y',
  FDATE DATETIME DEFAULT NULL,
  FUSER VARCHAR(30) DEFAULT '',
  FFORM VARCHAR(50) DEFAULT '',
  LDATE DATETIME DEFAULT NULL,
  LUSER VARCHAR(30) DEFAULT '',
  LFORM VARCHAR(50) DEFAULT '',
  PRIMARY KEY (BMA_CODE)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE B_Item (
  BIT_CODE VARCHAR(30) NOT NULL,
  BIT_CUST_CODE VARCHAR(30) DEFAULT NULL,
  BIT_NAME VARCHAR(50) DEFAULT '',
  BIT_SPEC VARCHAR(100) DEFAULT '',
  BIT_UNIT VARCHAR(1) DEFAULT '1',
  BIT_CLASS VARCHAR(1) DEFAULT '1',
  BCU_CODE VARCHAR(30) DEFAULT NULL,
  BCU_CODE2 VARCHAR(30) DEFAULT NULL,
  BMA_CODE VARCHAR(30) DEFAULT NULL,
  BIT_NETWGT DECIMAL(19, 7) DEFAULT 0,
  BIT_SPOOLWGT DECIMAL(19, 7) DEFAULT 0,
  BIT_SAFEQTY DECIMAL(19, 7) DEFAULT 0,
  BIT_PACKUNIT INT DEFAULT 1,
  BIT_FILLER VARCHAR(1000) DEFAULT '',
  BIT_FIFOYN VARCHAR(1) DEFAULT 'N',
  BIT_LOTYN VARCHAR(1) DEFAULT 'Y',
  BIT_PRELOTYN VARCHAR(1) DEFAULT 'N',
  BIT_GU1_1 VARCHAR(20) DEFAULT '000',
  BIT_GU1_2 VARCHAR(20) DEFAULT '000',
  BIT_GU1_3 VARCHAR(20) DEFAULT '000',
  BIT_GU2_1 VARCHAR(20) DEFAULT '000',
  BIT_GU2_2 VARCHAR(20) DEFAULT '000',
  BIT_GU2_3 VARCHAR(20) DEFAULT '000',
  BIT_GU3_1 VARCHAR(20) DEFAULT '000',
  BIT_GU3_2 VARCHAR(20) DEFAULT '000',
  BIT_GU3_3 VARCHAR(20) DEFAULT '000',
  BIT_DISDATE DATETIME DEFAULT NULL,
  BIT_BOXTYPE VARCHAR(100) DEFAULT '',
  BIT_PRICE DECIMAL(19, 7) DEFAULT 0,
  BIT_ST DECIMAL(19, 7) DEFAULT 0,
  BIT_PRODUCTGU VARCHAR(1) DEFAULT '1',
  BIT_USEYN VARCHAR(1) DEFAULT 'Y',
  BIT_SER VARCHAR(8) DEFAULT NULL,
  BIT_LIFEDAY INT DEFAULT 0,
  BIT_KPIYN VARCHAR(1) DEFAULT 'N',
  FDATE DATETIME DEFAULT NULL,
  FUSER VARCHAR(30) DEFAULT '',
  FFORM VARCHAR(50) DEFAULT '',
  LDATE DATETIME DEFAULT NULL,
  LUSER VARCHAR(30) DEFAULT '',
  LFORM VARCHAR(50) DEFAULT '',
  PRIMARY KEY (BIT_CODE)
) DEFAULT CHARSET=utf8mb4;


CREATE TABLE C_CommonCode (
  CCC_CODE INT NOT NULL,
  CCC_MCODE VARCHAR(10) DEFAULT '',
  CCC_MNAME VARCHAR(50) DEFAULT '',
  CCC_DCODE VARCHAR(20) DEFAULT '',
  CCC_DNAME VARCHAR(50) DEFAULT '',
  CCC_ETC1 VARCHAR(100) DEFAULT '',
  CCC_ETC2 VARCHAR(100) DEFAULT '',
  CCC_ETC3 VARCHAR(100) DEFAULT '',
  CCC_ETC4 VARCHAR(100) DEFAULT '',
  CCC_ETC5 VARCHAR(100) DEFAULT '',
  CCC_FILLER VARCHAR(1000) DEFAULT '',
  CCC_COMMONYN VARCHAR(1) DEFAULT 'N',
  CCC_SYSTEMYN VARCHAR(1) DEFAULT 'N',
  CCC_USEYN VARCHAR(1) DEFAULT 'Y',
  FDATE DATETIME DEFAULT NULL,
  FUSER VARCHAR(30) DEFAULT '',
  FFORM VARCHAR(50) DEFAULT '',
  LDATE DATETIME DEFAULT NULL,
  LUSER VARCHAR(30) DEFAULT '',
  LFORM VARCHAR(50) DEFAULT '',
  PRIMARY KEY (CCC_CODE)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE B_WorkTime (
  BWT_CODE INT NOT NULL,
  BWT_DATE DATETIME NOT NULL,
  BWT_PROGU VARCHAR(3) DEFAULT '',
  BWT_STIME DATETIME NOT NULL,
  BWT_ETIME DATETIME NOT NULL,
  BWT_NSTIME DATETIME NOT NULL,
  BWT_FILLER NVARCHAR(1000) DEFAULT '',
  FDATE DATETIME DEFAULT NULL,
  FUSER NVARCHAR(30) DEFAULT '',
  FFORM NVARCHAR(50) DEFAULT '',
  LDATE DATETIME DEFAULT NULL,
  LUSER NVARCHAR(30) DEFAULT '',
  LFORM NVARCHAR(50) DEFAULT '',
  PRIMARY KEY (BWT_CODE)
) DEFAULT CHARSET=utf8mb4;
